entities:
  - canonical: us food and drug administration
    aliases:
      - fda
      - food and drug administration
  - canonical: quality management system
    aliases:
      - qms
      - quality system
