#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG_PATH="$SCRIPT_DIR/services/litellm/config.yaml"
PROFILE="${1:-${YAR_PROFILE:-dev}}"
MASTER_KEY='os.environ/LITELLM_MASTER_KEY'
OPENROUTER_KEY='os.environ/OPENROUTER_API_KEY'
OPENAI_KEY='os.environ/OPENAI_API_KEY'

case "$PROFILE" in
	dev)
		TUNA_TARGET="openai/mistralai/mistral-small-2603"
		SALMON_TARGET="openai/google/gemini-3.1-flash-lite-preview"
		SHRIMP_TARGET="openai/perplexity/pplx-embed-v1-0.6b"
		TUNA_COMMENT="mistralai/mistral-small-2603 via OpenRouter"
		SALMON_COMMENT="google/gemini-3.1-flash-lite-preview via OpenRouter"
		SHRIMP_COMMENT="perplexity/pplx-embed-v1-0.6b via OpenRouter"
		TUNA_API_BASE="https://openrouter.ai/api/v1"
		SALMON_API_BASE="https://openrouter.ai/api/v1"
		SHRIMP_API_BASE="https://openrouter.ai/api/v1"
		TUNA_API_KEY="$OPENROUTER_KEY"
		SALMON_API_KEY="$OPENROUTER_KEY"
		SHRIMP_API_KEY="$OPENROUTER_KEY"
		;;
	work)
		TUNA_TARGET="openai/anthropic/claude-sonnet-4"
		SALMON_TARGET="$TUNA_TARGET"
		SHRIMP_TARGET="openai/text-embedding-3-small"
		TUNA_COMMENT="Claude Sonnet via OpenRouter"
		SALMON_COMMENT="same Claude Sonnet target as tuna"
		SHRIMP_COMMENT="text-embedding-3-small via OpenAI"
		TUNA_API_BASE="https://openrouter.ai/api/v1"
		SALMON_API_BASE="https://openrouter.ai/api/v1"
		SHRIMP_API_BASE="https://api.openai.com/v1"
		TUNA_API_KEY="$OPENROUTER_KEY"
		SALMON_API_KEY="$OPENROUTER_KEY"
		SHRIMP_API_KEY="$OPENAI_KEY"
		;;
	*)
		echo "Unsupported LiteLLM profile: $PROFILE" >&2
		exit 1
		;;
esac

mkdir -p "$(dirname "$CONFIG_PATH")"

cat > "$CONFIG_PATH" <<LITELLM_EOF
# LiteLLM Unified Config for YAR ($PROFILE)
# Auto-generated by scripts/generate_litellm_config.sh
#
# YAR uses:
#   - LLM_MODEL=tuna              → $TUNA_COMMENT
#   - EMBEDDING_MODEL=shrimp      → $SHRIMP_COMMENT
# Extra aliases:
#   - salmon                      → $SALMON_COMMENT

model_list:
  - model_name: tuna
    litellm_params:
      model: $TUNA_TARGET
      api_base: $TUNA_API_BASE
      api_key: $TUNA_API_KEY
    model_info:
      mode: chat
      supports_function_calling: true

  - model_name: salmon
    litellm_params:
      model: $SALMON_TARGET
      api_base: $SALMON_API_BASE
      api_key: $SALMON_API_KEY
    model_info:
      mode: chat
      supports_function_calling: true

  - model_name: shrimp
    litellm_params:
      model: $SHRIMP_TARGET
      api_base: $SHRIMP_API_BASE
      api_key: $SHRIMP_API_KEY

general_settings:
  master_key: $MASTER_KEY
  complete_response_logging: false
  allow_requests_on_db_unavailable: true
  disable_spend_logs: true
  disable_error_logs: true

litellm_settings:
  drop_params: true
  set_verbose: false
  ssl_verify: false
  cache: false
  json_logs: false
  num_retries: 3
  request_timeout: 120
  stream_options: { 'include_usage': true }
  default_litellm_params:
    encoding_format: float
LITELLM_EOF
